import Foundation

struct StoryboardProject {
    let projectDirectory: URL
    let swiftWebPackageDirectory: URL

    private var markerFile: URL {
        projectDirectory.appendingPathComponent(".swiftweb-storyboard")
    }

    func materialize(force: Bool) throws {
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: projectDirectory.path) {
            let isManagedDirectory = fileManager.fileExists(atPath: markerFile.path)
            if !force, !isManagedDirectory {
                throw CLIError(
                    message: "storyboard directory already exists and is not managed by swift-web: \(projectDirectory.path)",
                    exitCode: 73
                )
            }
            if force {
                try fileManager.removeItem(at: projectDirectory)
            } else if isManagedDirectory {
                try removeOwnedGeneratedFiles()
            }
        }

        try fileManager.createDirectory(at: projectDirectory, withIntermediateDirectories: true)
        for file in files {
            try write(file)
        }
    }

    private func removeOwnedGeneratedFiles() throws {
        let fileManager = FileManager.default
        let paths = [
            "Package.swift",
            "README.md",
            "Sources",
        ]
        for path in paths {
            let url = projectDirectory.appendingPathComponent(path)
            if fileManager.fileExists(atPath: url.path) {
                try fileManager.removeItem(at: url)
            }
        }
    }

    private var files: [TemplateFile] {
        [
            TemplateFile(path: ".swiftweb-storyboard", contents: "managed by swift-web\n"),
            TemplateFile(path: "Package.swift", contents: packageSwift),
            TemplateFile(path: "README.md", contents: readme),
            TemplateFile(path: "Sources/SwiftWebStoryboard/App.swift", contents: appSwift),
            TemplateFile(path: "Sources/SwiftWebStoryboard/Routes/StoryboardPage.swift", contents: storyboardPageSwift),
            TemplateFile(path: "Sources/SwiftWebStoryboard/Components/StoryboardInputs.swift", contents: storyboardInputsSwift),
        ]
    }

    private func write(_ file: TemplateFile) throws {
        let url = projectDirectory.appendingPathComponent(file.path)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try file.contents.write(to: url, atomically: true, encoding: .utf8)
    }

    private var packageSwift: String {
        """
        // swift-tools-version: 6.4

        import PackageDescription

        let package = Package(
            name: "SwiftWebStoryboard",
            platforms: [
                .macOS("26.2"),
            ],
            products: [
                .library(name: "SwiftWebStoryboard", targets: ["SwiftWebStoryboard"]),
            ],
            dependencies: [
                .package(path: "\(Self.swiftStringLiteral(swiftWebPackageDirectory.path))"),
                .package(url: "https://github.com/1amageek/swift-html.git", from: "0.1.0"),
            ],
            targets: [
                .target(
                    name: "SwiftWebStoryboard",
                    dependencies: [
                        .product(name: "SwiftHTML", package: "swift-html"),
                        .product(name: "SwiftWeb", package: "swift-web"),
                        .product(name: "SwiftWebUI", package: "swift-web"),
                    ],
                    swiftSettings: [
                        .enableUpcomingFeature("ApproachableConcurrency"),
                    ]
                ),
            ],
            swiftLanguageModes: [.v6]
        )
        """
    }

    private var readme: String {
        """
        # SwiftWeb Storyboard

        This package is generated by `swift-web storyboard`.

        It exists only to inspect SwiftWebUI component styles across themes, design styles, component states, and basic form controls. The app source package is not modified.

        ```bash
        swift-web storyboard --package-path \(Self.shellPath(projectDirectory.deletingLastPathComponent().deletingLastPathComponent().path))
        ```

        Storyboard launchers live inside this managed Storyboard package under `.swiftweb/generated`. They are generated from the same runtime path used by `swift-web dev`, but they are scoped to `.swiftweb/storyboard` so the user's app source is not modified.
        """
    }

    private var appSwift: String {
        """
        import SwiftWeb

        public struct SwiftWebStoryboard: SwiftWeb.App {
            public init() {}

            public var body: some AppContent {
                Redirect("/", to: "/storyboard")
                StoryboardPage()
            }
        }
        """
    }

    private var storyboardPageSwift: String {
        """
        import SwiftHTML
        import SwiftWeb
        import SwiftWebUI

        @Page("/storyboard")
        struct StoryboardPage {
            var title: String {
                get async {
                    "SwiftWebUI Storyboard"
                }
            }

            var description: String? {
                get async {
                    "Generated component style storyboard for SwiftWebUI."
                }
            }

            @HTMLBuilder
            func body() -> some HTML {
                style {
                    rawHTML(storyboardCSS)
                }

                main(.class("storyboard-page")) {
                    VStack(spacing: .xlarge) {
                        StoryboardHeader()
                        StoryboardMatrix()
                        StoryboardMaterials()
                        StoryboardHugFill()
                        StoryboardTypography()
                        StoryboardButtons()
                        StoryboardStates()
                        StoryboardMedia()
                        StoryboardStatus()
                        StoryboardInputs()
                        StoryboardForms()
                        StoryboardContainers()
                        StoryboardCollections()
                        StoryboardLazy()
                        StoryboardLayout()
                        StoryboardNavigation()
                        StoryboardFooter()
                    }
                    .frame(maxWidth: "960px")
                    .padding(.horizontal, "24px")
                    .padding(.vertical, "56px")
                }
                .environment(\\.theme, .light)
                .environment(\\.styleSystem, .swiftWeb)
            }
        }

        // MARK: - Reusable shells

        // A full-width section: a leading-aligned title block plus a card body
        // whose children stack with comfortable spacing. Fills the page column.
        struct StoryboardSection<Content: HTML>: Component {
            let heading: String
            let subtitle: String
            let content: Content

            init(_ heading: String, _ subtitle: String, @HTMLBuilder content: () -> Content) {
                self.heading = heading
                self.subtitle = subtitle
                self.content = content()
            }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .medium) {
                    VStack(alignment: .leading, spacing: .xsmall) {
                        Heading(heading, level: .section)
                        Text(subtitle, tone: .muted)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Card {
                        VStack(alignment: .leading, spacing: .large) {
                            content
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }

        // Inline monospace chip. ThemeStylesheet does not style bare `<code>`, so
        // the chrome is applied explicitly here.
        struct StoryboardCodeChip: Component {
            let text: String
            init(_ text: String) { self.text = text }

            var body: some HTML {
                Text(text, as: .code)
                    .padding(.all, "2px 8px")
                    .background("var(--swui-surface-raised)")
                    .cornerRadius("6px")
                    .style {
                        .border("1px solid var(--swui-border)")
                        .fontFamily("var(--swui-mono-font-family)")
                        .fontSize("0.85em")
                    }
            }
        }

        // A small labeled panel used inside the layout and lazy galleries.
        struct StoryboardMiniPanel<Content: HTML>: Component {
            let heading: String
            let content: Content
            init(_ heading: String, @HTMLBuilder content: () -> Content) {
                self.heading = heading
                self.content = content()
            }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .small) {
                    Text(heading, as: .small, tone: .muted)
                    content
                }
                .padding(.all, "16px")
                .background("var(--swui-surface-raised)")
                .cornerRadius("12px")
                .style { .border("1px solid var(--swui-border)") }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }

        // A tinted swatch that either hugs its content or fills the parent, so the
        // two sizing intents can be compared side by side.
        struct StoryboardSwatch: Component {
            enum Mode { case hug, fill }
            let label: String
            let mode: Mode

            var body: some HTML {
                let chip = HStack(spacing: .small) {
                    Badge(mode == .hug ? "fixedSize()" : "frame(maxWidth: .infinity)")
                    Text(label, tone: .muted)
                }
                .padding(.all, "12px 16px")
                .background("color-mix(in srgb, var(--swui-accent) 12%, var(--swui-surface-raised))")
                .cornerRadius("12px")
                .style { .border("1px solid color-mix(in srgb, var(--swui-accent) 32%, transparent)") }

                switch mode {
                case .hug:
                    chip.fixedSize()
                case .fill:
                    chip.frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Header / Footer

        struct StoryboardHeader: Component {
            var body: some HTML {
                VStack(alignment: .leading, spacing: .small) {
                    Badge("SwiftWebUI")
                    Heading("Component Storyboard", level: .page)
                    Text(
                        "A per-component gallery across themes and design styles. Every component either hugs its content or fills the available space \\u{2014} and that intent is always explicit.",
                        tone: .muted
                    )
                    HStack(spacing: .small) {
                        ButtonLink("View components", href: "#components", prominence: .primary)
                        Link("Documentation", href: "#")
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }

        struct StoryboardFooter: Component {
            var body: some HTML {
                VStack(alignment: .center, spacing: .small) {
                    Divider()
                    Text("Rendered with SwiftWebUI", as: .small, tone: .muted)
                }
                .frame(maxWidth: .infinity, alignment: .center)
            }
        }

        // MARK: - Theme x StyleSystem matrix

        // Renders the same sample under every theme/style-system pairing. Each cell
        // applies its own .environment(\\.theme:)/.environment(\\.styleSystem:) so the
        // nested ThemeScope rethemes backgrounds, surfaces, and controls independently.
        struct StoryboardMatrix: Component {
            var body: some HTML {
                StoryboardSection(
                    "Theme \\u{00D7} Design style",
                    "The same sample under every theme and design style. Each cell is a self-contained scope; backgrounds, surfaces, and controls all retheme."
                ) {
                    Grid(minColumnWidth: "280px", spacing: .large) {
                        StoryboardMatrixCell(theme: .light, themeLabel: "Light", style: .swiftWeb, styleLabel: "SwiftWeb")
                        StoryboardMatrixCell(theme: .light, themeLabel: "Light", style: .material, styleLabel: "Material")
                        StoryboardMatrixCell(theme: .light, themeLabel: "Light", style: .liquidGlass, styleLabel: "Liquid Glass")
                        StoryboardMatrixCell(theme: .dark, themeLabel: "Dark", style: .swiftWeb, styleLabel: "SwiftWeb")
                        StoryboardMatrixCell(theme: .dark, themeLabel: "Dark", style: .material, styleLabel: "Material")
                        StoryboardMatrixCell(theme: .dark, themeLabel: "Dark", style: .liquidGlass, styleLabel: "Liquid Glass")
                    }
                }
            }
        }

        struct StoryboardMatrixCell: Component {
            let theme: Theme
            let themeLabel: String
            let style: StyleSystem
            let styleLabel: String

            var body: some HTML {
                VStack(alignment: .leading, spacing: .small) {
                    // Labels stay outside the scope so they read against the page theme.
                    HStack(spacing: .small) {
                        Badge(themeLabel)
                        Badge(styleLabel)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    StoryboardMatrixSample()
                        .environment(\\.theme, theme)
                        .environment(\\.styleSystem, style)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }

        struct StoryboardMatrixSample: Component {
            var body: some HTML {
                Card {
                    VStack(alignment: .leading, spacing: .small) {
                        Heading("Preview", level: .subsection)
                        Text("Body copy adopts the theme tokens.", tone: .muted)
                        HStack(spacing: .small) {
                            Button("Primary", prominence: .primary)
                            Button("Secondary")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        HStack(spacing: .small) {
                            Badge("Badge")
                            ValueDisplay(label: "Value", value: 42)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "12px")
            }
        }

        // MARK: - Materials & Glass

        // The unified material primitive. Every chrome surface composes one shared
        // recipe; a level only scales the fill translucency. Under Liquid Glass the
        // recipe adds backdrop blur, a specular rim, and SVG refraction \\u{2014}
        // shown here over a vivid backdrop so the blur reads. Solid styles render
        // the same levels as opaque surfaces (compare the matrix above).
        struct StoryboardMaterials: Component {
            var body: some HTML {
                StoryboardSection(
                    "Materials & Glass",
                    "One recipe behind every surface. Levels scale the fill; Liquid Glass adds blur, a specular rim, and refraction. The stages below are scoped to Liquid Glass so the glass reads."
                ) {
                    Text("Material levels", as: .strong)
                    StoryboardGlassStage {
                        Grid(minColumnWidth: "150px", spacing: .medium) {
                            StoryboardMaterialSwatch("Ultra thin", code: ".ultraThinMaterial", material: .ultraThinMaterial)
                            StoryboardMaterialSwatch("Thin", code: ".thinMaterial", material: .thinMaterial)
                            StoryboardMaterialSwatch("Regular", code: ".regularMaterial", material: .regularMaterial)
                            StoryboardMaterialSwatch("Thick", code: ".thickMaterial", material: .thickMaterial)
                            StoryboardMaterialSwatch("Ultra thick", code: ".ultraThickMaterial", material: .ultraThickMaterial)
                            StoryboardMaterialSwatch("Bar", code: ".bar", material: .bar)
                        }
                    }

                    Divider()

                    Text("glassEffect(in:) and glass buttons", as: .strong)
                    StoryboardGlassStage {
                        HStack(spacing: .medium) {
                            Text("Regular glass")
                                .padding(.all, "12px 18px")
                                .glassEffect(.regular, in: .capsule)
                            Text("Tinted + interactive")
                                .padding(.all, "12px 18px")
                                .glassEffect(.regular.tint("var(--swui-accent)").interactive(), in: .capsule)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)

                        HStack(spacing: .small) {
                            Button("Glass", prominence: .primary)
                                .buttonStyle(.glass)
                            Button("Glass prominent", prominence: .primary)
                                .buttonStyle(.glassProminent)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
                .environment(\\.styleSystem, .liquidGlass)
            }
        }

        // A vivid backdrop so a material/glass surface's backdrop-filter blur and
        // refraction read clearly. The gradient is the stage's own background, so
        // children blur it through `backdrop-filter`.
        struct StoryboardGlassStage<Content: HTML>: Component {
            let content: Content
            init(@HTMLBuilder content: () -> Content) { self.content = content() }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .medium) {
                    content
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "20px")
                .cornerRadius("16px")
                .style {
                    .background("radial-gradient(440px 220px at 12% 16%, #ff7a7a, transparent 62%), radial-gradient(460px 240px at 88% 18%, #5b8cff, transparent 62%), radial-gradient(560px 280px at 50% 120%, #2dd4a7, transparent 60%), #0f172a")
                    .border("1px solid var(--swui-border)")
                }
            }
        }

        // A labeled panel filled with a material level. `.background(_:in:)` applies
        // the shared recipe; the level only changes the fill translucency.
        struct StoryboardMaterialSwatch: Component {
            let title: String
            let code: String
            let material: Material
            init(_ title: String, code: String, material: Material) {
                self.title = title
                self.code = code
                self.material = material
            }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .xsmall) {
                    Text(title, as: .strong)
                    Text(code, as: .small, tone: .muted)
                }
                .padding(.all, "16px")
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(material, in: .rect(cornerRadius: 16))
            }
        }

        // MARK: - Hug vs Fill (centerpiece)

        struct StoryboardHugFill: Component {
            var body: some HTML {
                StoryboardSection(
                    "Hug vs Fill",
                    "Shrinking and expanding components are completely separate. fixedSize() hugs; frame(maxWidth: .infinity) fills."
                ) {
                    Text("In a VStack, fill stretches the cross axis", as: .strong)
                    VStack(alignment: .leading, spacing: .small) {
                        StoryboardSwatch(label: "stays at its content width", mode: .hug)
                        StoryboardSwatch(label: "stretches to the full column width", mode: .fill)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    Text("In an HStack, fill grows along the main axis", as: .strong)
                    HStack(spacing: .small) {
                        StoryboardSwatch(label: "hug", mode: .hug)
                        StoryboardSwatch(label: "grows", mode: .fill)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    Text("Spacer pushes siblings apart", as: .strong)
                    HStack(spacing: .small) {
                        Badge("leading")
                        Spacer()
                        Badge("trailing")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Typography

        struct StoryboardTypography: Component {
            var body: some HTML {
                StoryboardSection(
                    "Typography",
                    "Headings and text tones resolve to theme tokens."
                ) {
                    Heading("Page heading", level: .page)
                    Heading("Section heading", level: .section)
                    Heading("Subsection heading", level: .subsection)
                    Text("Body copy uses the base text token and a comfortable line height for long-form reading.")
                    Text("Muted secondary copy for captions and hints.", tone: .muted)
                    HStack(spacing: .medium) {
                        Text("Strong", as: .strong)
                        Text("Small print", as: .small, tone: .muted)
                        StoryboardCodeChip("inline.code()")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Buttons

        struct StoryboardButtons: Component {
            var body: some HTML {
                StoryboardSection(
                    "Buttons",
                    "Prominence, button styles, and links. Glass styles read as Liquid Glass under that design style and degrade to a solid surface elsewhere."
                ) {
                    Toolbar {
                        Button("Primary", prominence: .primary)
                        Button("Secondary")
                        Button("Glass")
                            .buttonStyle(.glass)
                        Button("Glass prominent", prominence: .primary)
                            .buttonStyle(.glassProminent)
                        Button("Plain")
                            .buttonStyle(.plain)
                        ButtonLink("Link", href: "#", prominence: .secondary)
                        Link("Anchor", href: "#")
                    }
                }
            }
        }

        // MARK: - States

        // Control sizes, tint, and disabled. The primary button background resolves
        // its tint on the button element itself, so .tint(_:) overrides take effect.
        struct StoryboardStates: Component {
            var body: some HTML {
                StoryboardSection(
                    "States",
                    "Control sizes, tint, and disabled \\u{2014} the same components under different conditions."
                ) {
                    Text("Control sizes", as: .strong)
                    HStack(spacing: .small) {
                        Button("Mini", prominence: .primary)
                            .controlSize(.mini)
                        Button("Small", prominence: .primary)
                            .controlSize(.small)
                        Button("Regular", prominence: .primary)
                            .controlSize(.regular)
                        Button("Large", prominence: .primary)
                            .controlSize(.large)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    Text("Tint", as: .strong)
                    HStack(spacing: .small) {
                        Button("Accent", prominence: .primary)
                            .tint(.accent)
                        Button("Danger", prominence: .primary)
                            .tint(.danger)
                        Button("Custom", prominence: .primary)
                            .tint(.css("#22a06b"))
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    Text("Disabled", as: .strong)
                    HStack(spacing: .small) {
                        Button("Enabled", prominence: .primary)
                        Button("Disabled", prominence: .primary)
                            .disabled()
                        SubmitButton("Submit")
                            .disabled()
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Media

        struct StoryboardMedia: Component {
            var body: some HTML {
                StoryboardSection(
                    "Media",
                    "SF Symbol names render as symbol spans; Label pairs an icon with a title."
                ) {
                    HStack(spacing: .medium) {
                        Image(systemName: "star.fill")
                        Image(systemName: "bell.badge")
                        Image(systemName: "gearshape")
                        Image(systemName: "person.crop.circle")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    HStack(spacing: .large) {
                        Label("Verified", systemImage: "checkmark.seal.fill")
                        Label("Favorite", systemImage: "heart.fill")
                        Label("Pinned", systemImage: "pin.fill")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Status

        struct StoryboardStatus: Component {
            var body: some HTML {
                StoryboardSection(
                    "Status",
                    "ProgressView and Gauge compose the ultra-thin material track; DisclosureGroup composes the regular material like Card."
                ) {
                    Grid(minColumnWidth: "240px", spacing: .large) {
                        StoryboardMiniPanel("ProgressView") {
                            VStack(alignment: .leading, spacing: .medium) {
                                ProgressView("Uploading", value: 0.35)
                                ProgressView("Rendering", value: 0.7)
                                ProgressView("Loading")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        StoryboardMiniPanel("Gauge") {
                            VStack(alignment: .leading, spacing: .medium) {
                                Gauge(value: 0.25, label: "Disk")
                                Gauge(value: 0.62, label: "CPU")
                                Gauge(value: 0.9, label: "Memory")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                    }

                    DisclosureGroup("Advanced options", isExpanded: true) {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Nested content reveals when expanded.", tone: .muted)
                            Label("Verbose logging", systemImage: "doc.text")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    DisclosureGroup("Collapsed by default") {
                        Text("Hidden until toggled.", tone: .muted)
                    }
                }
            }
        }

        // MARK: - Forms

        struct StoryboardForms: Component {
            var body: some HTML {
                StoryboardSection(
                    "Forms",
                    "A Form posts to an action. SubmitButtons carry name/value; Labels caption fields."
                ) {
                    Form(action: "/subscribe", method: .post) {
                        VStack(alignment: .leading, spacing: .medium) {
                            Label("Email address", systemImage: "envelope")
                            HStack(spacing: .small) {
                                SubmitButton("Subscribe", prominence: .primary)
                                    .name("intent")
                                    .value("subscribe")
                                SubmitButton("Unsubscribe")
                                    .name("intent")
                                    .value("unsubscribe")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
            }
        }

        // MARK: - Containers

        struct StoryboardContainers: Component {
            var body: some HTML {
                StoryboardSection(
                    "Containers",
                    "Badges and value displays \\u{2014} components that hug their content."
                ) {
                    HStack(spacing: .small) {
                        Badge("Default")
                        Badge("Ready")
                        Badge("Beta")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    HStack(spacing: .medium) {
                        ValueDisplay(label: "Score", value: 42)
                        ValueDisplay(label: "Streak", value: 7)
                        ValueDisplay(label: "Grade", value: "A+")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Lists & Sections

        struct StoryboardCollections: Component {
            var body: some HTML {
                StoryboardSection(
                    "Lists & Sections",
                    "Grouped rows fill their container; Spacer separates leading and trailing content."
                ) {
                    Grid(minColumnWidth: "260px", spacing: .large) {
                        List {
                            ListRow {
                                Text("Wi-Fi")
                                Spacer()
                                Badge("On")
                            }
                            ListRow {
                                Text("Bluetooth")
                                Spacer()
                                Text("Off", tone: .muted)
                            }
                            ListRow {
                                Text("Updates")
                                Spacer()
                                Badge("3")
                            }
                        }

                        Section("Account", footer: "Signed in as ada@example.com") {
                            VStack(alignment: .leading, spacing: .small) {
                                Text("Profile")
                                Text("Security")
                                Text("Notifications")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                    }
                }
            }
        }

        // MARK: - Lazy containers & ScrollView

        struct StoryboardLazy: Component {
            var body: some HTML {
                StoryboardSection(
                    "Lazy containers & ScrollView",
                    "Lazy stacks and grids mark their scroll axis; ScrollView clips overflow on its axes."
                ) {
                    Grid(minColumnWidth: "240px", spacing: .large) {
                        StoryboardMiniPanel("LazyVStack") {
                            LazyVStack(alignment: .leading, spacing: .small) {
                                Badge("Row 1")
                                Badge("Row 2")
                                Badge("Row 3")
                            }
                        }
                        StoryboardMiniPanel("LazyHStack") {
                            LazyHStack(spacing: .small) {
                                Badge("A")
                                Badge("B")
                                Badge("C")
                            }
                        }
                        StoryboardMiniPanel("LazyVGrid") {
                            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: .small) {
                                Badge("1")
                                Badge("2")
                                Badge("3")
                                Badge("4")
                            }
                        }
                        StoryboardMiniPanel("LazyHGrid") {
                            LazyHGrid(rows: [GridItem(.fixed(28)), GridItem(.fixed(28))], spacing: .small) {
                                Badge("1")
                                Badge("2")
                                Badge("3")
                                Badge("4")
                            }
                        }
                    }

                    Divider()

                    Text("ScrollView (vertical, clipped to 160px)", as: .strong)
                    ScrollView(.vertical) {
                        VStack(alignment: .leading, spacing: .small) {
                            Badge("Item 01")
                            Badge("Item 02")
                            Badge("Item 03")
                            Badge("Item 04")
                            Badge("Item 05")
                            Badge("Item 06")
                            Badge("Item 07")
                            Badge("Item 08")
                            Badge("Item 09")
                            Badge("Item 10")
                        }
                        .padding(.all, "8px")
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, height: "160px")
                    .background("var(--swui-surface-raised)")
                    .cornerRadius("12px")
                    .style { .border("1px solid var(--swui-border)") }
                }
            }
        }

        // MARK: - Layout primitives

        struct StoryboardLayout: Component {
            var body: some HTML {
                StoryboardSection(
                    "Layout",
                    "Stacks, grids, and overlays \\u{2014} the primitives the rest is built from."
                ) {
                    Grid(minColumnWidth: "200px", spacing: .large) {
                        StoryboardMiniPanel("VStack") {
                            VStack(alignment: .leading, spacing: .small) {
                                Badge("Top")
                                Badge("Middle")
                                Badge("Bottom")
                            }
                        }
                        StoryboardMiniPanel("HStack") {
                            HStack(spacing: .small) {
                                Badge("A")
                                Badge("B")
                                Badge("C")
                            }
                        }
                        StoryboardMiniPanel("ZStack") {
                            ZStack(alignment: .center) {
                                Text(" ")
                                    .frame(width: "180px", height: "72px")
                                    .background("color-mix(in srgb, var(--swui-accent) 16%, transparent)")
                                    .cornerRadius("10px")
                                Badge("Overlay")
                            }
                        }
                    }
                }
            }
        }

        // MARK: - Navigation

        struct StoryboardNavigation: Component {
            var body: some HTML {
                StoryboardSection(
                    "Navigation",
                    "Navigation stacks hug their content and align to the leading edge."
                ) {
                    NavigationStack {
                        VStack(alignment: .leading, spacing: .small) {
                            NavigationLink("Overview", href: "#")
                            NavigationLink("Components", href: "#components")
                            NavigationLink("Tokens", href: "#tokens")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
            }
        }

        let storyboardCSS = \"\"\"
        .storyboard-page {
            min-height: 100vh;
            background:
                radial-gradient(1200px 520px at 50% -8%, color-mix(in srgb, var(--swui-accent) 10%, transparent), transparent),
                var(--swui-background);
            color: var(--swui-text);
            font-family: var(--swui-font-family);
        }

        .storyboard-page,
        .storyboard-page * {
            box-sizing: border-box;
        }
        \"\"\"
        """
    }

    private var storyboardInputsSwift: String {
        """
        import Foundation
        import SwiftHTML
        import SwiftWebUI

        public struct StoryboardInputs: ClientComponent, Sendable {
            @State private var name = "Ada"
            @State private var email = "ada@example.com"
            @State private var secret = "hunter2"
            @State private var style = "swift-web"
            @State private var enabled = true
            @State private var volume = 0.6
            @State private var density = 3
            @State private var theme = Theme.light
            @State private var notes = "Multi-line text editor."
            @State private var due = Date(timeIntervalSince1970: 1_718_000_000)
            @State private var accent = "#3366ff"
            @State private var segment = "list"
            @State private var scope = "all"
            @State private var tab = "summary"
            @State private var query = ""
            @State private var showsAlert = false
            @State private var showsConfirmation = false
            @State private var showsSheet = false
            @State private var showsPopover = false

            public init() {}

            public var body: some HTML {
                VStack(alignment: .stretch, spacing: .medium) {
                    VStack(alignment: .leading, spacing: .xsmall) {
                        Heading("Inputs")
                        Text(
                            "Client components hydrate and mutate local state on the page.",
                            tone: .muted
                        )
                    }

                    Grid(minColumnWidth: "240px", spacing: .large) {
                        VStack(alignment: .leading, spacing: .medium) {
                            TextField("Name", text: $name)
                            TextField("Email", text: $email, .type(.email), .required)
                                .textContentType(.emailAddress)
                                .keyboardType(.emailAddress)
                                .submitLabel(.go)
                            SecureField("Secret", text: $secret)
                            Picker("Design style", selection: $style) {
                                PickerOption("SwiftWeb", value: "swift-web")
                                PickerOption("Material", value: "material")
                                PickerOption("Liquid Glass", value: "liquid-glass")
                            }
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)

                        VStack(alignment: .leading, spacing: .medium) {
                            Toggle("Enabled", isOn: $enabled)
                            Slider(value: $volume, in: 0...1, step: 0.05)
                            Stepper("Density", value: $density, in: 0...8)
                            ValueDisplay(label: "Density", value: density)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }

                    Divider()

                    Grid(minColumnWidth: "240px", spacing: .large) {
                        VStack(alignment: .leading, spacing: .medium) {
                            TextEditor(text: $notes)
                            ColorPicker("Accent", selection: $accent)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)

                        VStack(alignment: .leading, spacing: .medium) {
                            DatePicker("Due date", selection: $due)
                            DatePicker(
                                "Starts at",
                                selection: $due,
                                displayedComponents: [.date, .hourAndMinute]
                            )
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }

                    Divider()

                    VStack(alignment: .leading, spacing: .small) {
                        Text("Theme switcher", as: .small, tone: .muted)
                        ThemeSwitcher(selection: $theme, themes: [.light, .dark, .system])
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    Grid(minColumnWidth: "240px", spacing: .large) {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Picker \\u{2014} segmented", as: .small, tone: .muted)
                            Picker("View", selection: $segment) {
                                PickerOption("List", value: "list")
                                PickerOption("Grid", value: "grid")
                                PickerOption("Columns", value: "columns")
                            }
                            .pickerStyle(.segmented)

                            Text("Picker \\u{2014} inline", as: .small, tone: .muted)
                            Picker("Scope", selection: $scope) {
                                PickerOption("All", value: "all")
                                PickerOption("Unread", value: "unread")
                                PickerOption("Flagged", value: "flagged")
                            }
                            .pickerStyle(.inline)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)

                        VStack(alignment: .leading, spacing: .small) {
                            Text("Menu", as: .small, tone: .muted)
                            Menu("Options") {
                                Button("Duplicate") {}
                                Button("Move\\u{2026}") {}
                                Button("Delete") {}
                            }
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }

                    Divider()

                    VStack(alignment: .leading, spacing: .small) {
                        Text("TabView", as: .small, tone: .muted)
                        TabView(selection: $tab) {
                            Tab("Summary", systemImage: "doc.text", value: "summary") {
                                Text("Summary panel content.", tone: .muted)
                            }
                            Tab("Activity", systemImage: "chart.bar", value: "activity") {
                                Text("Activity panel content.", tone: .muted)
                            }
                            Tab("Settings", systemImage: "gear", value: "settings") {
                                Text("Settings panel content.", tone: .muted)
                            }
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    VStack(alignment: .leading, spacing: .small) {
                        Text("Searchable", as: .small, tone: .muted)
                        List {
                            ListRow { Text("Inbox") }
                            ListRow { Text("Drafts") }
                            ListRow { Text("Sent") }
                        }
                        .searchable(text: $query)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)

                    Divider()

                    VStack(alignment: .leading, spacing: .small) {
                        Text("Presentation", as: .small, tone: .muted)
                        HStack(spacing: .small) {
                            Button("Alert") { showsAlert = true }
                            Button("Confirm") { showsConfirmation = true }
                            Button("Sheet") { showsSheet = true }
                            Button("Popover") { showsPopover = true }
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .alert("Delete this draft?", isPresented: $showsAlert) {
                        Button("Delete", action: Action.post("/storyboard/delete"))
                    } message: {
                        Text("This action cannot be undone.")
                    }
                    .confirmationDialog(
                        "Discard changes?",
                        isPresented: $showsConfirmation,
                        titleVisibility: .visible
                    ) {
                        Button("Discard", action: Action.post("/storyboard/discard"))
                        Button("Keep editing") { showsConfirmation = false }
                    }
                    .sheet(isPresented: $showsSheet) {
                        VStack(alignment: .leading, spacing: .medium) {
                            Heading("Sheet", level: .section)
                            Text(
                                "A sheet composes the thick material and lifts to the top layer.",
                                tone: .muted
                            )
                            Button("Done") { showsSheet = false }
                        }
                    }
                    .popover(isPresented: $showsPopover) {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Popover content anchored to its source.", tone: .muted)
                            Button("Close") { showsPopover = false }
                        }
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
        """
    }

    private static func swiftStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
    }

    private static func shellPath(_ path: String) -> String {
        "'" + path.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
