import Foundation

struct StoryboardProject {
    let projectDirectory: URL
    let swiftWebPackageDirectory: URL

    private var markerFile: URL {
        projectDirectory.appendingPathComponent(".swiftweb-storyboard")
    }

    func materialize(force: Bool) throws {
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: projectDirectory.path) {
            let isManagedDirectory = fileManager.fileExists(atPath: markerFile.path)
            if !force, !isManagedDirectory {
                throw StoryboardError.storyboardDirectoryNotManaged(projectDirectory)
            }
            if force {
                try fileManager.removeItem(at: projectDirectory)
            } else if isManagedDirectory {
                try removeOwnedGeneratedFiles()
            }
        }

        try fileManager.createDirectory(at: projectDirectory, withIntermediateDirectories: true)
        for file in files {
            try write(file)
        }
    }

    private func removeOwnedGeneratedFiles() throws {
        let fileManager = FileManager.default
        let paths = [
            "Package.swift",
            "README.md",
            "Sources",
        ]
        for path in paths {
            let url = projectDirectory.appendingPathComponent(path)
            if fileManager.fileExists(atPath: url.path) {
                try fileManager.removeItem(at: url)
            }
        }
    }

    private var files: [TemplateFile] {
        [
            TemplateFile(path: ".swiftweb-storyboard", contents: "managed by swift-web\n"),
            TemplateFile(path: "Package.swift", contents: packageSwift),
            TemplateFile(path: "README.md", contents: readme),
            TemplateFile(path: "Sources/SwiftWebStoryboard/App.swift", contents: appSwift),
            TemplateFile(path: "Sources/SwiftWebStoryboard/Routes/StoryboardPage.swift", contents: storyboardPageSwift),
            TemplateFile(path: "Sources/SwiftWebStoryboard/Components/StoryboardCatalog.swift", contents: storyboardCatalogSwift),
        ]
    }

    private func write(_ file: TemplateFile) throws {
        let url = projectDirectory.appendingPathComponent(file.path)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try file.contents.write(to: url, atomically: true, encoding: .utf8)
    }

    private var packageSwift: String {
        return """
        // swift-tools-version: 6.3

        import PackageDescription

        let package = Package(
            name: "SwiftWebStoryboard",
            platforms: [
                .macOS("26.2"),
            ],
            products: [
                .library(name: "SwiftWebStoryboard", targets: ["SwiftWebStoryboard"]),
            ],
            dependencies: [
                .package(path: "\(Self.swiftStringLiteral(swiftWebPackageDirectory.path))"),
                .package(url: "https://github.com/1amageek/swift-html.git", from: "0.3.0"),
            ],
            targets: [
                .target(
                    name: "SwiftWebStoryboard",
                    dependencies: [
                        .product(name: "SwiftHTML", package: "swift-html"),
                        .product(name: "SwiftWeb", package: "swift-web"),
                        .product(name: "SwiftWebUI", package: "swift-web"),
                    ],
                    swiftSettings: [
                        .enableUpcomingFeature("ApproachableConcurrency"),
                    ]
                ),
            ],
            swiftLanguageModes: [.v6]
        )
        """
    }

    private var readme: String {
        """
        # SwiftWeb Storyboard

        This package is generated by `swift-web storyboard`.

        It exists only to inspect SwiftWebUI component styles across themes, style systems, component states, and basic form controls. The app source package is not modified.

        ```bash
        swift-web storyboard --package-path \(Self.shellPath(projectDirectory.deletingLastPathComponent().deletingLastPathComponent().path))
        ```

        Storyboard launchers live inside this managed Storyboard package under `.swiftweb/generated`. They are generated from the same runtime path used by `swift-web dev`, but they are scoped to `.swiftweb/storyboard` so the user's app source is not modified.
        """
    }

    private var appSwift: String {
        """
        import SwiftWeb

        public struct SwiftWebStoryboard: SwiftWeb.App {
            public init() {}

            public var body: some AppContent {
                Redirect("/", to: "/storyboard")
                StoryboardPage()
            }
        }
        """
    }

    private var storyboardPageSwift: String {
        """
        import SwiftHTML
        import SwiftWeb
        import SwiftWebUI

        @Page("/storyboard")
        struct StoryboardPage {
            var title: String {
                get async {
                    "SwiftWebUI Storyboard"
                }
            }

            var description: String? {
                get async {
                    "A design-system catalog of every SwiftWebUI component."
                }
            }

            // The page emits its own chrome CSS, then the catalog. The catalog is a
            // single ClientComponent so the sidebar selection and the global
            // appearance/style-system controls drive the detail and inspector live.
            @HTMLBuilder
            func body() -> some HTML {
                style {
                    rawHTML(storyboardCSS)
                }

                StoryboardCatalog()
            }
        }

        let storyboardCSS = \"\"\"
        html { scroll-behavior: smooth; }
        body { margin: 0; }
        .storyboard-page {
            min-height: 100vh;
            background:
                radial-gradient(1200px 520px at 50% -8%, color-mix(in srgb, var(--swui-accent) 8%, transparent), transparent),
                var(--swui-background);
            color: var(--swui-text);
            font-family: var(--swui-font-family);
        }

        .storyboard-page,
        .storyboard-page * {
            box-sizing: border-box;
        }

        /* Offset in-page anchor jumps so the sticky top bar never covers a target. */
        .storyboard-page [id] {
            scroll-margin-top: 72px;
        }
        \"\"\"
        """
    }

    private var storyboardCatalogSwift: String {
        """
        import Foundation
        import SwiftHTML
        import SwiftWebUI

        // MARK: - Style mapping

        private func catalogStyleSystem(for id: String) -> StyleSystem {
            switch id {
            case "material":
                return .material
            case "liquid-glass":
                return .liquidGlass
            default:
                return .swiftWeb
            }
        }

        // MARK: - Registry

        // One component entry. `id` is the selection key shared by the sidebar, the
        // detail router, and the inspector. `code` and `summary` are the metadata the
        // inspector shows; the live demo is matched to `id` in the detail router.
        struct CatalogItem: Identifiable, Sendable {
            let id: String
            let name: String
            let code: String
            let summary: String
        }

        // A sidebar group of components.
        struct CatalogCategory: Identifiable, Sendable {
            let id: String
            let title: String
            let items: [CatalogItem]
        }

        // The catalog model. It drives the sidebar list and the inspector metadata;
        // CatalogDetail maps a selection id to its live demo.
        let catalogCategories: [CatalogCategory] = [
            CatalogCategory(id: "foundations", title: "Foundations", items: [
                CatalogItem(id: "typography", name: "Typography", code: "Heading(_:level:) · Text(_:tone:)", summary: "Headings and text tones resolve to theme tokens."),
                CatalogItem(id: "color", name: "Color & tint", code: ".tint(.accent)", summary: "tint(_:) recolors a control's accent; semantic and custom colors are available."),
                CatalogItem(id: "materials", name: "Materials", code: ".background(.regularMaterial, in:)", summary: "One recipe behind every surface; a level only scales the fill. Liquid Glass adds blur, a specular rim, and refraction."),
                CatalogItem(id: "glass", name: "Glass", code: ".glassEffect(.regular, in:)", summary: "glassEffect(in:) frosts any surface; GlassEffectContainer shares one glass context across siblings."),
            ]),
            CatalogCategory(id: "buttons", title: "Buttons & actions", items: [
                CatalogItem(id: "button", name: "Button", code: "Button(_:prominence:)", summary: "Prominence sets the visual weight."),
                CatalogItem(id: "button-styles", name: "Button styles", code: ".buttonStyle(.glass)", summary: "Glass styles read as Liquid Glass under that style system and degrade to a solid surface elsewhere."),
                CatalogItem(id: "control-sizes", name: "Control sizes", code: ".controlSize(.large)", summary: "controlSize(_:) scales padding and type together."),
                CatalogItem(id: "button-states", name: "Tint & disabled", code: ".disabled()", summary: "tint(_:) recolors; disabled() dims and blocks interaction."),
                CatalogItem(id: "links", name: "Links", code: "ButtonLink(_:href:) · Link(_:href:)", summary: "ButtonLink looks like a button; Link is plain inline navigation."),
            ]),
            CatalogCategory(id: "inputs", title: "Inputs & controls", items: [
                CatalogItem(id: "textfield", name: "TextField", code: "TextField(_:text:)", summary: "Text entry with input type, validation, and content-type hints."),
                CatalogItem(id: "securefield", name: "SecureField", code: "SecureField(_:text:)", summary: "Masked entry for secrets."),
                CatalogItem(id: "texteditor", name: "TextEditor", code: "TextEditor(text:)", summary: "Multi-line text entry that composes the thin material."),
                CatalogItem(id: "toggle", name: "Toggle", code: "Toggle(_:isOn:)", summary: "A boolean switch; the track composes the unified material."),
                CatalogItem(id: "slider", name: "Slider", code: "Slider(value:in:step:)", summary: "A continuous value across a range with an optional step."),
                CatalogItem(id: "stepper", name: "Stepper", code: "Stepper(_:value:in:)", summary: "Increment or decrement a discrete value within bounds."),
                CatalogItem(id: "datepicker", name: "DatePicker", code: "DatePicker(_:selection:displayedComponents:)", summary: "displayedComponents selects date, time, or both."),
                CatalogItem(id: "colorpicker", name: "ColorPicker", code: "ColorPicker(_:selection:)", summary: "A native color well bound to a hex string."),
                CatalogItem(id: "form", name: "Form", code: "Form(action:method:)", summary: "A Form posts to an action; SubmitButtons carry name/value."),
            ]),
            CatalogCategory(id: "pickers", title: "Pickers & menus", items: [
                CatalogItem(id: "picker", name: "Picker", code: ".pickerStyle(.segmented)", summary: "pickerStyle(_:) chooses dropdown, segmented, inline, or menu."),
                CatalogItem(id: "menu", name: "Menu", code: "Menu(_:content:)", summary: "A pull-down list of actions disclosed on demand."),
            ]),
            CatalogCategory(id: "containers", title: "Containers", items: [
                CatalogItem(id: "card", name: "Card", code: "Card { }", summary: "The primary surface; composes the regular material."),
                CatalogItem(id: "badge", name: "Badge", code: "Badge(_:)", summary: "A compact status pill that hugs its label."),
                CatalogItem(id: "valuedisplay", name: "ValueDisplay", code: "ValueDisplay(label:value:)", summary: "A labeled readout for a single metric."),
                CatalogItem(id: "list", name: "List", code: "List { ListRow { } }", summary: "Grouped rows that fill their container; Spacer splits leading and trailing."),
                CatalogItem(id: "section", name: "Section", code: "Section(_:footer:)", summary: "A titled group with an optional footer."),
                CatalogItem(id: "disclosuregroup", name: "DisclosureGroup", code: "DisclosureGroup(_:isExpanded:)", summary: "An expandable region; composes the regular material like Card."),
                CatalogItem(id: "grid", name: "Grid", code: "Grid(minColumnWidth:spacing:)", summary: "A responsive grid that wraps at a minimum column width."),
                CatalogItem(id: "lazy", name: "Lazy stacks & grids", code: "LazyVStack · LazyVGrid(columns:)", summary: "Lazy containers mark their scroll axis for large collections."),
                CatalogItem(id: "scrollview", name: "ScrollView", code: "ScrollView(.vertical)", summary: "Clips overflow on its axis and scrolls within a fixed frame."),
            ]),
            CatalogCategory(id: "status", title: "Status", items: [
                CatalogItem(id: "progressview", name: "ProgressView", code: "ProgressView(_:value:)", summary: "A determinate bar with a value, or an indeterminate spinner without one."),
                CatalogItem(id: "gauge", name: "Gauge", code: "Gauge(value:label:)", summary: "A compact readout of a value within a range."),
            ]),
            CatalogCategory(id: "navigation", title: "Navigation & tabs", items: [
                CatalogItem(id: "navigationstack", name: "NavigationStack", code: "NavigationStack { NavigationLink }", summary: "A single-column stack; NavigationLink pushes a destination."),
                CatalogItem(id: "tabview", name: "TabView", code: "TabView(selection:) { Tab }", summary: "Switches panels; the tab bar composes interactive glass."),
                CatalogItem(id: "searchable", name: "Searchable", code: ".searchable(text:)", summary: "Adds a search field bound to a query over a collection."),
            ]),
            CatalogCategory(id: "presentation", title: "Presentation", items: [
                CatalogItem(id: "alert", name: "Alert & dialog", code: ".alert(_:isPresented:)", summary: "alert(_:isPresented:) and confirmationDialog(...) interrupt for a decision."),
                CatalogItem(id: "sheet", name: "Sheet & popover", code: ".sheet(isPresented:)", summary: "sheet(isPresented:) lifts a panel; popover(isPresented:) anchors to its source."),
            ]),
            CatalogCategory(id: "layout", title: "Layout", items: [
                CatalogItem(id: "stacks", name: "Stacks", code: "VStack · HStack · ZStack", summary: "VStack and HStack arrange along an axis; ZStack overlays."),
                CatalogItem(id: "spacer", name: "Spacer & Divider", code: "Spacer() · Divider()", summary: "Spacer pushes siblings apart; Divider draws a hairline rule."),
                CatalogItem(id: "hug-fill", name: "Hug vs fill", code: ".fixedSize() · .frame(maxWidth: .infinity)", summary: "fixedSize() hugs the content; frame(maxWidth: .infinity) fills the column."),
            ]),
            CatalogCategory(id: "media", title: "Media", items: [
                CatalogItem(id: "image", name: "Image", code: "Image(systemName:)", summary: "An SF Symbol name renders as a symbol span."),
                CatalogItem(id: "label", name: "Label", code: "Label(_:systemImage:)", summary: "Pairs an icon with a title."),
            ]),
        ]

        let catalogDefaultSelection = "typography"

        private func catalogItem(for id: String) -> CatalogItem? {
            for category in catalogCategories {
                for item in category.items where item.id == id {
                    return item
                }
            }
            return nil
        }

        private func catalogCategory(for itemID: String) -> CatalogCategory? {
            for category in catalogCategories where category.items.contains(where: { $0.id == itemID }) {
                return category
            }
            return nil
        }

        // MARK: - Shells

        // Inline monospace chip naming the call site of the entry's component.
        private struct CatalogCodeChip: Component {
            let text: String
            init(_ text: String) { self.text = text }

            var body: some HTML {
                Text(text, as: .code)
                    .padding(.all, "2px 8px")
                    .background("var(--swui-surface-raised)")
                    .cornerRadius("6px")
                    .style {
                        .border("1px solid var(--swui-border)")
                        .fontFamily("var(--swui-mono-font-family)")
                        .fontSize("0.82em")
                    }
            }
        }

        // A captioned slot inside a demo, used to label a single variant.
        private struct CatalogVariant<Content: HTML>: Component {
            let label: String
            let content: Content

            init(_ label: String, @HTMLBuilder content: () -> Content) {
                self.label = label
                self.content = content()
            }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .xsmall) {
                    Text(label, as: .small, tone: .muted)
                    content
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        }

        // A vivid backdrop so a material/glass surface's backdrop blur and refraction
        // read. The gradient is the stage's own background; children blur it through
        // `backdrop-filter` when the style system is Liquid Glass.
        private struct CatalogGlassStage<Content: HTML>: Component {
            let content: Content
            init(@HTMLBuilder content: () -> Content) { self.content = content() }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .medium) {
                    content
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "20px")
                .cornerRadius("16px")
                .style {
                    .background("radial-gradient(440px 220px at 12% 16%, #ff7a7a, transparent 62%), radial-gradient(460px 240px at 88% 18%, #5b8cff, transparent 62%), radial-gradient(560px 280px at 50% 120%, #2dd4a7, transparent 60%), #0f172a")
                    .border("1px solid var(--swui-border)")
                }
            }
        }

        // A labeled panel filled with a material level via `.background(_:in:)`.
        private struct CatalogMaterialSwatch: Component {
            let title: String
            let code: String
            let material: Material

            init(_ title: String, code: String, material: Material) {
                self.title = title
                self.code = code
                self.material = material
            }

            var body: some HTML {
                VStack(alignment: .leading, spacing: .xsmall) {
                    Text(title, as: .strong)
                    Text(code, as: .small, tone: .muted)
                }
                .padding(.all, "16px")
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(material, in: .rect(cornerRadius: 16))
            }
        }

        // MARK: - Chrome: top bar

        // The sticky global control bar spanning all three panes. The theme and
        // style-system controls drive the catalog's @State; the enclosing scope
        // re-applies `.environment` on every change, so the whole catalog rethemes
        // live. The bar composes the `.bar` material, dogfooding the style system it
        // switches.
        private struct CatalogTopBar: Component {
            let theme: Binding<Theme>
            let styleID: Binding<String>

            var body: some HTML {
                HStack(spacing: .large) {
                    HStack(spacing: .small) {
                        Badge("SwiftWebUI")
                        Text("Component Storyboard", as: .strong)
                    }

                    Spacer()

                    HStack(spacing: .large) {
                        HStack(spacing: .xsmall) {
                            Text("Appearance", as: .small, tone: .muted)
                            ThemeSwitcher(selection: theme, themes: [.light, .dark, .system])
                        }
                        HStack(spacing: .xsmall) {
                            Text("Style", as: .small, tone: .muted)
                            Picker("Style System", selection: styleID) {
                                PickerOption("SwiftWeb", value: "swift-web")
                                PickerOption("Material", value: "material")
                                PickerOption("Liquid Glass", value: "liquid-glass")
                            }
                            .pickerStyle(.segmented)
                        }
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "12px 20px")
                .background(.bar, in: .rect(cornerRadius: 0))
                .style {
                    .custom("position", "sticky")
                    .custom("top", "0")
                    .custom("z-index", "40")
                    .custom("border-bottom", "1px solid var(--swui-border)")
                }
            }
        }

        // MARK: - Chrome: sidebar

        // The component picker. Categories are headings; each item is a button that
        // sets the selection @State, re-rendering the detail and inspector.
        private struct CatalogSidebar: Component {
            let selection: Binding<String>

            var body: some HTML {
                VStack(alignment: .leading, spacing: .large) {
                    ForEach(catalogCategories) { category in
                        VStack(alignment: .leading, spacing: .xsmall) {
                            Text(category.title, as: .small, tone: .muted)
                                .style {
                                    .custom("text-transform", "uppercase")
                                    .custom("letter-spacing", "0.04em")
                                    .fontWeight("600")
                                }
                            ForEach(category.items) { item in
                                CatalogSidebarRow(item: item, selection: selection)
                            }
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
                .frame(width: "248px", alignment: .leading)
                .padding(.all, "18px 14px")
                .style {
                    .custom("position", "sticky")
                    .custom("top", "56px")
                    .custom("align-self", "flex-start")
                    .custom("max-height", "calc(100vh - 56px)")
                    .custom("overflow-y", "auto")
                    .custom("border-right", "1px solid var(--swui-border)")
                }
            }
        }

        // One sidebar row: a plain button whose selected state tints the label and
        // raises a subtle accent background.
        private struct CatalogSidebarRow: Component {
            let item: CatalogItem
            let selection: Binding<String>

            var body: some HTML {
                Button(action: { selection.wrappedValue = item.id }) {
                    Text(item.name)
                }
                .buttonStyle(.plain)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "6px 10px")
                .background(selection.wrappedValue == item.id ? "color-mix(in srgb, var(--swui-accent) 14%, transparent)" : "transparent")
                .cornerRadius("8px")
                .style {
                    .custom("color", selection.wrappedValue == item.id ? "var(--swui-accent)" : "var(--swui-text)")
                    .fontWeight(selection.wrappedValue == item.id ? "600" : "450")
                    .fontSize("0.9em")
                }
            }
        }

        // MARK: - Chrome: inspector

        // The right pane. It shows the selected component's API signature and summary,
        // then the sibling components in the same section for quick context.
        private struct CatalogInspector: Component {
            let selection: String

            var body: some HTML {
                VStack(alignment: .leading, spacing: .large) {
                    inspectorMetadata()
                    inspectorSection()
                }
                .frame(width: "300px", alignment: .leading)
                .padding(.all, "20px 18px")
                .style {
                    .custom("position", "sticky")
                    .custom("top", "56px")
                    .custom("align-self", "flex-start")
                    .custom("max-height", "calc(100vh - 56px)")
                    .custom("overflow-y", "auto")
                    .custom("border-left", "1px solid var(--swui-border)")
                }
            }

            @HTMLBuilder
            private func inspectorMetadata() -> some HTML {
                if let item = catalogItem(for: selection) {
                    VStack(alignment: .leading, spacing: .large) {
                        VStack(alignment: .leading, spacing: .xsmall) {
                            Text("API", as: .small, tone: .muted)
                            CatalogCodeChip(item.code)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)

                        VStack(alignment: .leading, spacing: .xsmall) {
                            Text("Summary", as: .small, tone: .muted)
                            Text(item.summary, tone: .muted)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }

            @HTMLBuilder
            private func inspectorSection() -> some HTML {
                if let category = catalogCategory(for: selection) {
                    VStack(alignment: .leading, spacing: .xsmall) {
                        Text("In this section", as: .small, tone: .muted)
                        ForEach(category.items) { item in
                            inspectorSectionRow(item)
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }

            @HTMLBuilder
            private func inspectorSectionRow(_ item: CatalogItem) -> some HTML {
                if item.id == selection {
                    Text(item.name, as: .strong)
                } else {
                    Text(item.name, tone: .muted)
                }
            }
        }

        // MARK: - Detail router

        // The center pane. A registry-driven header names the component; the demo is
        // routed by category to keep each switch small, then by component id.
        private struct CatalogDetail: Component {
            let selection: String
            let name: Binding<String>
            let email: Binding<String>
            let secret: Binding<String>
            let notes: Binding<String>
            let enabled: Binding<Bool>
            let volume: Binding<Double>
            let density: Binding<Int>
            let due: Binding<Date>
            let accent: Binding<String>
            let pick: Binding<String>
            let segment: Binding<String>
            let scope: Binding<String>
            let menuPick: Binding<String>
            let tab: Binding<String>
            let query: Binding<String>
            let showsAlert: Binding<Bool>
            let showsConfirmation: Binding<Bool>
            let showsSheet: Binding<Bool>
            let showsPopover: Binding<Bool>

            var body: some HTML {
                VStack(alignment: .leading, spacing: .large) {
                    detailHeader()
                    Card {
                        VStack(alignment: .leading, spacing: .medium) {
                            detailDemo()
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.all, "28px 32px")
            }

            @HTMLBuilder
            private func detailHeader() -> some HTML {
                if let item = catalogItem(for: selection) {
                    Heading(item.name, level: .page)
                }
            }

            @HTMLBuilder
            private func detailDemo() -> some HTML {
                switch catalogCategory(for: selection)?.id ?? "foundations" {
                case "buttons":
                    ButtonsDetail(selection: selection)
                case "inputs":
                    InputsDetail(
                        selection: selection,
                        name: name,
                        email: email,
                        secret: secret,
                        notes: notes,
                        enabled: enabled,
                        volume: volume,
                        density: density,
                        due: due,
                        accent: accent
                    )
                case "pickers":
                    PickersDetail(selection: selection, pick: pick, segment: segment, scope: scope, menuPick: menuPick)
                case "containers":
                    ContainersDetail(selection: selection)
                case "status":
                    StatusDetail(selection: selection)
                case "navigation":
                    NavigationDetail(selection: selection, tab: tab, query: query)
                case "presentation":
                    PresentationDetail(
                        selection: selection,
                        showsAlert: showsAlert,
                        showsConfirmation: showsConfirmation,
                        showsSheet: showsSheet,
                        showsPopover: showsPopover
                    )
                case "layout":
                    LayoutDetail(selection: selection)
                case "media":
                    MediaDetail(selection: selection)
                default:
                    FoundationsDetail(selection: selection)
                }
            }
        }

        // MARK: - Detail: Foundations

        private struct FoundationsDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "color":
                    HStack(spacing: .small) {
                        Button("Accent", prominence: .primary)
                            .tint(.accent)
                        Button("Danger", prominence: .primary)
                            .tint(.danger)
                        Button("Custom", prominence: .primary)
                            .tint(.css("#22a06b"))
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                case "materials":
                    CatalogGlassStage {
                        Grid(minColumnWidth: "150px", spacing: .medium) {
                            CatalogMaterialSwatch("Ultra thin", code: ".ultraThinMaterial", material: .ultraThinMaterial)
                            CatalogMaterialSwatch("Thin", code: ".thinMaterial", material: .thinMaterial)
                            CatalogMaterialSwatch("Regular", code: ".regularMaterial", material: .regularMaterial)
                            CatalogMaterialSwatch("Thick", code: ".thickMaterial", material: .thickMaterial)
                            CatalogMaterialSwatch("Ultra thick", code: ".ultraThickMaterial", material: .ultraThickMaterial)
                            CatalogMaterialSwatch("Bar", code: ".bar", material: .bar)
                        }
                    }
                case "glass":
                    CatalogGlassStage {
                        GlassEffectContainer(spacing: .medium) {
                            Text("Regular glass")
                                .padding(.all, "12px 18px")
                                .glassEffect(.regular, in: .capsule)
                            Text("Tinted + interactive")
                                .padding(.all, "12px 18px")
                                .glassEffect(.regular.tint("var(--swui-accent)").interactive(), in: .capsule)
                        }

                        HStack(spacing: .small) {
                            Button("Glass", prominence: .primary)
                                .buttonStyle(.glass)
                            Button("Glass prominent", prominence: .primary)
                                .buttonStyle(.glassProminent)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                default:
                    Heading("Page heading", level: .page)
                    Heading("Section heading", level: .section)
                    Heading("Subsection heading", level: .subsection)
                    Text("Body copy uses the base text token and a comfortable line height for long-form reading.")
                    Text("Muted secondary copy for captions and hints.", tone: .muted)
                    HStack(spacing: .medium) {
                        Text("Strong", as: .strong)
                        Text("Small print", as: .small, tone: .muted)
                        CatalogCodeChip("inline.code()")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Detail: Buttons & actions

        private struct ButtonsDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "button-styles":
                    CatalogGlassStage {
                        HStack(spacing: .small) {
                            Button("Glass", prominence: .primary)
                                .buttonStyle(.glass)
                            Button("Glass prominent", prominence: .primary)
                                .buttonStyle(.glassProminent)
                            Button("Plain")
                                .buttonStyle(.plain)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                case "control-sizes":
                    HStack(spacing: .small) {
                        Button("Mini", prominence: .primary)
                            .controlSize(.mini)
                        Button("Small", prominence: .primary)
                            .controlSize(.small)
                        Button("Regular", prominence: .primary)
                            .controlSize(.regular)
                        Button("Large", prominence: .primary)
                            .controlSize(.large)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                case "button-states":
                    HStack(spacing: .small) {
                        Button("Enabled", prominence: .primary)
                        Button("Disabled", prominence: .primary)
                            .disabled()
                        SubmitButton("Submit")
                            .disabled()
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                case "links":
                    HStack(spacing: .small) {
                        ButtonLink("Primary link", href: "#", prominence: .primary)
                        ButtonLink("Secondary link", href: "#", prominence: .secondary)
                        Link("Anchor", href: "#")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                default:
                    HStack(spacing: .small) {
                        Button("Primary", prominence: .primary)
                        Button("Secondary")
                        Button("Plain")
                            .buttonStyle(.plain)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Detail: Inputs & controls

        private struct InputsDetail: Component {
            let selection: String
            let name: Binding<String>
            let email: Binding<String>
            let secret: Binding<String>
            let notes: Binding<String>
            let enabled: Binding<Bool>
            let volume: Binding<Double>
            let density: Binding<Int>
            let due: Binding<Date>
            let accent: Binding<String>

            var body: some HTML {
                switch selection {
                case "securefield":
                    SecureField("Secret", text: secret)
                case "texteditor":
                    TextEditor(text: notes)
                case "toggle":
                    Toggle("Enabled", isOn: enabled)
                case "slider":
                    Slider(value: volume, in: 0...1, step: 0.05)
                case "stepper":
                    Stepper("Density", value: density, in: 0...8)
                    ValueDisplay(label: "Density", value: density.wrappedValue)
                case "datepicker":
                    DatePicker("Due date", selection: due)
                    DatePicker(
                        "Starts at",
                        selection: due,
                        displayedComponents: [.date, .hourAndMinute]
                    )
                case "colorpicker":
                    ColorPicker("Accent", selection: accent)
                case "form":
                    Form(action: "/subscribe", method: .post) {
                        VStack(alignment: .leading, spacing: .medium) {
                            Label("Email address", systemImage: "envelope")
                            HStack(spacing: .small) {
                                SubmitButton("Subscribe", prominence: .primary)
                                    .name("intent")
                                    .value("subscribe")
                                SubmitButton("Unsubscribe")
                                    .name("intent")
                                    .value("unsubscribe")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                default:
                    TextField("Name", text: name)
                    TextField("Email", text: email, .type(.email), .required)
                        .textContentType(.emailAddress)
                        .keyboardType(.emailAddress)
                        .submitLabel(.go)
                }
            }
        }

        // MARK: - Detail: Pickers & menus

        private struct PickersDetail: Component {
            let selection: String
            let pick: Binding<String>
            let segment: Binding<String>
            let scope: Binding<String>
            let menuPick: Binding<String>

            var body: some HTML {
                switch selection {
                case "menu":
                    Menu("Options") {
                        Button("Duplicate") {}
                        Button("Move…") {}
                        Button("Delete") {}
                    }
                default:
                    CatalogVariant("Automatic (dropdown)") {
                        Picker("Export format", selection: pick) {
                            PickerOption("JSON", value: "json")
                            PickerOption("CSV", value: "csv")
                            PickerOption("XML", value: "xml")
                        }
                    }
                    CatalogVariant("Segmented") {
                        Picker("View", selection: segment) {
                            PickerOption("List", value: "list")
                            PickerOption("Grid", value: "grid")
                            PickerOption("Columns", value: "columns")
                        }
                        .pickerStyle(.segmented)
                    }
                    CatalogVariant("Inline") {
                        Picker("Scope", selection: scope) {
                            PickerOption("All", value: "all")
                            PickerOption("Unread", value: "unread")
                            PickerOption("Flagged", value: "flagged")
                        }
                        .pickerStyle(.inline)
                    }
                    CatalogVariant("Menu") {
                        Picker("Sort by", selection: menuPick) {
                            PickerOption("Name", value: "name")
                            PickerOption("Date", value: "date")
                            PickerOption("Size", value: "size")
                        }
                        .pickerStyle(.menu)
                    }
                }
            }
        }

        // MARK: - Detail: Containers

        private struct ContainersDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "badge":
                    HStack(spacing: .small) {
                        Badge("Default")
                        Badge("Ready")
                        Badge("Beta")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                case "valuedisplay":
                    HStack(spacing: .medium) {
                        ValueDisplay(label: "Score", value: 42)
                        ValueDisplay(label: "Streak", value: 7)
                        ValueDisplay(label: "Grade", value: "A+")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                case "list":
                    List {
                        ListRow {
                            Text("Wi-Fi")
                            Spacer()
                            Badge("On")
                        }
                        ListRow {
                            Text("Bluetooth")
                            Spacer()
                            Text("Off", tone: .muted)
                        }
                        ListRow {
                            Text("Updates")
                            Spacer()
                            Badge("3")
                        }
                    }
                case "section":
                    Section("Account", footer: "Signed in as ada@example.com") {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Profile")
                            Text("Security")
                            Text("Notifications")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                case "disclosuregroup":
                    DisclosureGroup("Advanced options", isExpanded: true) {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Nested content reveals when expanded.", tone: .muted)
                            Label("Verbose logging", systemImage: "doc.text")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    DisclosureGroup("Collapsed by default") {
                        Text("Hidden until toggled.", tone: .muted)
                    }
                case "grid":
                    Grid(minColumnWidth: "120px", spacing: .small) {
                        Badge("Cell 1")
                        Badge("Cell 2")
                        Badge("Cell 3")
                        Badge("Cell 4")
                    }
                case "lazy":
                    Grid(minColumnWidth: "220px", spacing: .large) {
                        CatalogVariant("LazyVStack") {
                            LazyVStack(alignment: .leading, spacing: .small) {
                                Badge("Row 1")
                                Badge("Row 2")
                                Badge("Row 3")
                            }
                        }
                        CatalogVariant("LazyHStack") {
                            LazyHStack(spacing: .small) {
                                Badge("A")
                                Badge("B")
                                Badge("C")
                            }
                        }
                        CatalogVariant("LazyVGrid") {
                            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: .small) {
                                Badge("1")
                                Badge("2")
                                Badge("3")
                                Badge("4")
                            }
                        }
                        CatalogVariant("LazyHGrid") {
                            LazyHGrid(rows: [GridItem(.fixed(28)), GridItem(.fixed(28))], spacing: .small) {
                                Badge("1")
                                Badge("2")
                                Badge("3")
                                Badge("4")
                            }
                        }
                    }
                case "scrollview":
                    ScrollView(.vertical) {
                        VStack(alignment: .leading, spacing: .small) {
                            Badge("Item 01")
                            Badge("Item 02")
                            Badge("Item 03")
                            Badge("Item 04")
                            Badge("Item 05")
                            Badge("Item 06")
                            Badge("Item 07")
                            Badge("Item 08")
                        }
                        .padding(.all, "8px")
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, height: "160px")
                    .background("var(--swui-surface-raised)")
                    .cornerRadius("12px")
                    .style { .border("1px solid var(--swui-border)") }
                default:
                    Card {
                        VStack(alignment: .leading, spacing: .small) {
                            Heading("Card title", level: .subsection)
                            Text("Cards group related content on the shared surface material.", tone: .muted)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Detail: Status

        private struct StatusDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "gauge":
                    Gauge(value: 0.25, label: "Disk")
                    Gauge(value: 0.62, label: "CPU")
                    Gauge(value: 0.9, label: "Memory")
                default:
                    ProgressView("Uploading", value: 0.35)
                    ProgressView("Rendering", value: 0.7)
                    ProgressView("Loading")
                }
            }
        }

        // MARK: - Detail: Navigation & tabs

        private struct NavigationDetail: Component {
            let selection: String
            let tab: Binding<String>
            let query: Binding<String>

            var body: some HTML {
                switch selection {
                case "tabview":
                    TabView(selection: tab) {
                        Tab("Summary", systemImage: "doc.text", value: "summary") {
                            Text("Summary panel content.", tone: .muted)
                        }
                        Tab("Activity", systemImage: "chart.bar", value: "activity") {
                            Text("Activity panel content.", tone: .muted)
                        }
                        Tab("Settings", systemImage: "gear", value: "settings") {
                            Text("Settings panel content.", tone: .muted)
                        }
                    }
                case "searchable":
                    List {
                        ListRow { Text("Inbox") }
                        ListRow { Text("Drafts") }
                        ListRow { Text("Sent") }
                    }
                    .searchable(text: query)
                default:
                    NavigationStack {
                        VStack(alignment: .leading, spacing: .small) {
                            NavigationLink("Overview", href: "#")
                            NavigationLink("Components", href: "#components")
                            NavigationLink("Tokens", href: "#tokens")
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
            }
        }

        // MARK: - Detail: Presentation

        private struct PresentationDetail: Component {
            let selection: String
            let showsAlert: Binding<Bool>
            let showsConfirmation: Binding<Bool>
            let showsSheet: Binding<Bool>
            let showsPopover: Binding<Bool>

            var body: some HTML {
                switch selection {
                case "sheet":
                    HStack(spacing: .small) {
                        Button("Show sheet") { showsSheet.wrappedValue = true }
                        Button("Show popover") { showsPopover.wrappedValue = true }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .sheet(isPresented: showsSheet) {
                        VStack(alignment: .leading, spacing: .medium) {
                            Heading("Sheet", level: .section)
                            Text("A sheet composes the thick material and lifts to the top layer.", tone: .muted)
                            Button("Done") { showsSheet.wrappedValue = false }
                        }
                    }
                    .popover(isPresented: showsPopover) {
                        VStack(alignment: .leading, spacing: .small) {
                            Text("Popover content anchored to its source.", tone: .muted)
                            Button("Close") { showsPopover.wrappedValue = false }
                        }
                    }
                default:
                    HStack(spacing: .small) {
                        Button("Show alert") { showsAlert.wrappedValue = true }
                        Button("Show confirmation") { showsConfirmation.wrappedValue = true }
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .alert("Delete this draft?", isPresented: showsAlert) {
                        Button("Delete", action: Action.post("/storyboard/delete"))
                    } message: {
                        Text("This action cannot be undone.")
                    }
                    .confirmationDialog(
                        "Discard changes?",
                        isPresented: showsConfirmation,
                        titleVisibility: .visible
                    ) {
                        Button("Discard", action: Action.post("/storyboard/discard"))
                        Button("Keep editing") { showsConfirmation.wrappedValue = false }
                    }
                }
            }
        }

        // MARK: - Detail: Layout

        private struct LayoutDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "spacer":
                    HStack(spacing: .small) {
                        Badge("leading")
                        Spacer()
                        Badge("trailing")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    Divider()
                    Text("Above and below are separated by a Divider.", as: .small, tone: .muted)
                case "hug-fill":
                    HStack(spacing: .small) {
                        Badge("fixedSize()")
                        Text("stays at content width", tone: .muted)
                    }
                    .padding(.all, "12px 16px")
                    .background("color-mix(in srgb, var(--swui-accent) 12%, var(--swui-surface-raised))")
                    .cornerRadius("12px")
                    .style { .border("1px solid color-mix(in srgb, var(--swui-accent) 32%, transparent)") }
                    .fixedSize()

                    HStack(spacing: .small) {
                        Badge("frame(maxWidth: .infinity)")
                        Text("stretches to the full column", tone: .muted)
                    }
                    .padding(.all, "12px 16px")
                    .background("color-mix(in srgb, var(--swui-accent) 12%, var(--swui-surface-raised))")
                    .cornerRadius("12px")
                    .style { .border("1px solid color-mix(in srgb, var(--swui-accent) 32%, transparent)") }
                    .frame(maxWidth: .infinity, alignment: .leading)
                default:
                    Grid(minColumnWidth: "180px", spacing: .large) {
                        CatalogVariant("VStack") {
                            VStack(alignment: .leading, spacing: .small) {
                                Badge("Top")
                                Badge("Middle")
                                Badge("Bottom")
                            }
                        }
                        CatalogVariant("HStack") {
                            HStack(spacing: .small) {
                                Badge("A")
                                Badge("B")
                                Badge("C")
                            }
                        }
                        CatalogVariant("ZStack") {
                            ZStack(alignment: .center) {
                                Text(" ")
                                    .frame(width: "160px", height: "64px")
                                    .background("color-mix(in srgb, var(--swui-accent) 16%, transparent)")
                                    .cornerRadius("10px")
                                Badge("Overlay")
                            }
                        }
                    }
                }
            }
        }

        // MARK: - Detail: Media

        private struct MediaDetail: Component {
            let selection: String

            var body: some HTML {
                switch selection {
                case "label":
                    HStack(spacing: .large) {
                        Label("Verified", systemImage: "checkmark.seal.fill")
                        Label("Favorite", systemImage: "heart.fill")
                        Label("Pinned", systemImage: "pin.fill")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                default:
                    HStack(spacing: .medium) {
                        Image(systemName: "star.fill")
                        Image(systemName: "bell.badge")
                        Image(systemName: "gearshape")
                        Image(systemName: "person.crop.circle")
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
        }

        // MARK: - Catalog root

        /// The full component catalog as a single client component. It owns the
        /// selection plus every piece of demo state, so the sidebar drives the detail
        /// and inspector and the top-bar controls retheme the page live by re-applying
        /// the environment on each change.
        public struct StoryboardCatalog: ClientComponent, Sendable {
            @State private var selection = catalogDefaultSelection
            @State private var theme = Theme.light
            @State private var styleID = "swift-web"
            @State private var name = "Ada Lovelace"
            @State private var email = "ada@example.com"
            @State private var secret = "hunter2"
            @State private var notes = "Notes support multiple lines."
            @State private var enabled = true
            @State private var volume = 0.6
            @State private var density = 3
            @State private var due = Date(timeIntervalSince1970: 1_718_000_000)
            @State private var accent = "#3366ff"
            @State private var pick = "json"
            @State private var segment = "grid"
            @State private var scope = "all"
            @State private var menuPick = "name"
            @State private var tab = "summary"
            @State private var query = ""
            @State private var showsAlert = false
            @State private var showsConfirmation = false
            @State private var showsSheet = false
            @State private var showsPopover = false

            public init() {}

            public var body: some HTML {
                main(.class("storyboard-page")) {
                    VStack(spacing: .none) {
                        CatalogTopBar(theme: $theme, styleID: $styleID)
                        HStack(alignment: .top, spacing: .none) {
                            CatalogSidebar(selection: $selection)
                            CatalogDetail(
                                selection: selection,
                                name: $name,
                                email: $email,
                                secret: $secret,
                                notes: $notes,
                                enabled: $enabled,
                                volume: $volume,
                                density: $density,
                                due: $due,
                                accent: $accent,
                                pick: $pick,
                                segment: $segment,
                                scope: $scope,
                                menuPick: $menuPick,
                                tab: $tab,
                                query: $query,
                                showsAlert: $showsAlert,
                                showsConfirmation: $showsConfirmation,
                                showsSheet: $showsSheet,
                                showsPopover: $showsPopover
                            )
                            CatalogInspector(selection: selection)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
                .environment(\\.theme, theme)
                .environment(\\.styleSystem, catalogStyleSystem(for: styleID))
            }
        }
        """
    }

    private static func swiftStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
    }

    private static func shellPath(_ path: String) -> String {
        "'" + path.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
